### ISSUE TITLE
"ImageMagick doesn't appear to be installed."

### ISSUE THREAD

**Issue by kamok** [matthew342/simplecov-badge#7]
I get that when I run `rspec` on my console. But it is installed on my machine as I use the Paperclip gem. I also used the test of typing "identify" in the console to get a response.

What do I do?

**Comment by sKinkzer** [comment]
Make sure you have version 2.0.3 installed. The check for ImageMagick fails on 2.0.2 at least on OSX 10.11.

**Comment by unRARed** [comment]
Still broken for me per #9.
